name: Listing S3 buckets

on: 
  push:
    branches: 
      - master
  workflow_dispatch:

jobs: 
  listing_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: ${{ secrets.AWS_REGION}}
          role-to-assume: ${{ secrets.IAM_ROLE}}

      - name : List S3 Buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION}}
        run: |
          echo "Listing S3 buckets"
          aws s3 ls